### ISSUE TITLE
error: w2v in runAnalysis.py in the branch analysis_with_click

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/embiggen#162]
branch analysis_with_click:
get an error message when I run w2v in runAnalysis.py:

> Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/embiggen/runAnalysis.py", line 172, in <module>
    cli()
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ravanv/PycharmProjects/embiggen/runAnalysis.py", line 166, in w2v
    write_embeddings(output_file, model.embedding, reverse_dictionary)
  File "/Users/ravanv/PycharmProjects/embiggen/xn2v/utils/embedding_utils.py", line 104, in write_embeddings
    embed = get_embedding(x, embedding).numpy()
  File "/Users/ravanv/PycharmProjects/embiggen/xn2v/utils/embedding_utils.py", line 48, in get_embedding
    embedding = tf.nn.embedding_lookup(embedding, x)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/tensorflow_core/python/ops/embedding_ops.py", line 364, in embedding_lookup_v2
    return embedding_lookup(params, ids, "div", name, max_norm=max_norm)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/tensorflow_core/python/ops/embedding_ops.py", line 317, in embedding_lookup
    transform_fn=None)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/tensorflow_core/python/ops/embedding_ops.py", line 135, in _embedding_lookup_and_transform
    array_ops.gather(params[0], ids, name=name), ids, max_norm)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 3965, in gather
    return params.sparse_read(indices, name=name)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 640, in sparse_read
    self._handle, indices, dtype=self._dtype, name=name)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_resource_variable_ops.py", line 670, in resource_gather
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices = 9815 is not in [0, 9815) [Op:ResourceGather] name: embedding_lookup/

**Comment by pnrobinson** [comment]
This seems to be the issue:
indices = 9815 is not in [0, 9815) [Op:ResourceGather] name: embedding_lookup

**Comment by vidarmehr** [comment]
@pnrobinson I increased the vocabulary_size by 1 in xn2v/calculate_vocabulary_size. The code ran successfully. I am going to make a pull request. But, please let me know if you have any comment or correction on this. Thank you.
