### ISSUE TITLE
AttributeError with builtins.EnsmallenGraph

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/embiggen#248]
Guessing this is relevant to the updates for integrating ensmallen better. 
When running
`embedding, history = compute_node_embedding(cora, "CBOW", verbose=2)`
the following error is raised:

`Traceback (most recent call last):
  File "embiggen_test.py", line 15, in <module>
    embedding, history = compute_node_embedding(cora, "CBOW", verbose=2)
  File "/home/jhc/embiggen/embiggen/pipelines/compute_node_embedding.py", line 300, in compute_node_embedding
    if automatically_sort_by_decreasing_outbound_node_degree and node_embedding_method_name in REQUIRE_ZIPFIAN and not graph.has_nodes_sorted_by_decreasing_outbound_node_degree():
AttributeError: 'builtins.EnsmallenGraph' object has no attribute 'has_nodes_sorted_by_decreasing_outbound_node_degree'`

Similarly, for the following:
`embedding, history = compute_node_embedding(cora, "Siamese", verbose=2)`
the result is:

`Traceback (most recent call last):
  File "embiggen_test.py", line 15, in <module>
    embedding, history = compute_node_embedding(cora, "Siamese", verbose=2)
  File "/home/jhc/embiggen/embiggen/pipelines/compute_node_embedding.py", line 328, in compute_node_embedding
    graph.enable(
ValueError: The following arguments are not valid keyword arguments for this function.
{"vector_cumulative_node_degrees"}
 the available ones are:
{"cache_size", "vector_sources", "vector_outbounds", "vector_destinations"}`

**Comment by LucaCappelletti94** [comment]
Hello @caufieldjh, that suggests that the Ensmallen version you are using is deprecated. From where did you install it? If you'd like we can setup a call to understand what is going wrong and fix it.

**Comment by caufieldjh** [comment]
Thanks @LucaCappelletti94 - I tried a fresh rebuild of Ensmallen from source (from the develop branch) and now have some fresh errors upon loading the Cora graph:

Traceback (most recent call last):
  File "embiggen_test.py", line 10, in <module>
    cora = Cora()
  File "/home/jhc/.local/lib/python3.8/site-packages/ensmallen_graph/datasets/linqs/cora.py", line 109, in Cora
    return AutomaticallyRetrievedGraph(
  File "/home/jhc/.local/lib/python3.8/site-packages/ensmallen_graph/datasets/automatic_graph_retrieval.py", line 287, in __call__
    ) = edge_list_utils.build_optimal_lists_files(
ValueError: Neither nodes ID column or node types column were given!

**Comment by LucaCappelletti94** [comment]
Reproduced the error, on it!

**Comment by LucaCappelletti94** [comment]
Resolved, it was a recently introduced variable ghosting problem that only showed itself on graphs that require an additional preprocessing like Cora. Do let me know if everything runs smoothly!

**Comment by LucaCappelletti94** [comment]
Hello @caufieldjh, do feel free to open other issues for those errors (even though they are unclear), possibly they will be helpful in the future if someone else encounters them.
